language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

install:
  - python setup.py install
  - pip install -r requirements-dev.txt

script:
  - flake8 jekyll2nikola
  - python setup.py test

after_success:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: change
